import argparse
import json
import shutil
from pathlib import Path

REAL_ASSET_HINTS = {
    "broll/job_board_scroll.mp4": "Screen record scrolling a job board (LinkedIn/Indeed) filtered to enterprise marketing roles.",
    "broll/campaign_brief_scroll.mp4": "Screen record scrolling a campaign brief document (Google Doc or Word).",
    "broll/html_email_code.mp4": "Screen record HTML email code in VS Code or Cursor, slow scroll.",
    "broll/chatgpt_agent_prompt.mp4": "Screen record typing a campaign brief prompt into ChatGPT and the response streaming.",
    "broll/template_generator_output.mp4": "Screen record a generated HTML email rendering in a browser preview.",
    "broll/qa_checklist_scroll.mp4": "Screen record scrolling a QA checklist with checkmarks (Notion, Sheets, or Markdown).",
    "broll/zip_package_folder.mp4": "Screen record opening a ZIP/folder showing the full production package contents.",
    "broll/corporate_desk_setup.mp4": "Film or record a clean desk setup with monitor showing email/campaign work.",
    "broll/subscribe_end_card.mp4": "Branded end card with subscribe button animation (make in CapCut/Canva).",
    "motion/backgrounds/brief_to_zip_flow_map.mp4": "Animated flow map: Brief → AI Agent → HTML → QA → ZIP (make in Canva/After Effects/CapCut).",
    "motion/backgrounds/enterprise_grid_pulse.mp4": "Fallback background: dark navy grid with subtle teal pulse.",
    "motion/backgrounds/senioto_framework_map.mp4": "Hero motion graphic: LEARN → BUILD → GROW three-node animation (Canva/CapCut/After Effects).",
    "motion/end_cards/subscribe_end_card.mp4": "Subscribe end card with button pulse and next-video preview slot (CapCut/Canva).",
    "broll/workflow_montage_fast.mp4": "Fast montage: brief → ChatGPT → template → ZIP, quick cuts.",
    "broll/folder_chaos_scroll.mp4": "Screen record a messy project folder / cluttered notes scroll.",
    "broll/github_copilot_editing.mp4": "Screen record GitHub Copilot or Cursor editing code, README scroll.",
    "broll/roadmap_skill_stack.mp4": "Roadmap graphic: HTML Email → QA → Automation → AI Workflow → Enterprise Role (Canva/CapCut).",
    "talking_head/nat_intro_01.mp4": "Film hook takes: chest-up, dark backdrop, key light, direct eye contact.",
    "talking_head/nat_main_01.mp4": "Film bridging lines for mid sections (read from longform_script.md).",
    "talking_head/nat_cta_01.mp4": "Film closing CTA, slower and direct to camera.",
}

CHAPTER_CARD_HINT = "Chapter card: number + short title, midnight blue bg, teal underline sweep (build once in CapCut, duplicate)."


EXPORT_PRESETS = {
    "shorts": {"resolution": "1080x1920", "aspectRatio": "9:16", "format": "MP4", "fps": 30, "audioCodec": "AAC"},
    "longForm": {"resolution": "1920x1080", "aspectRatio": "16:9", "format": "MP4", "fps": 30, "audioCodec": "AAC"},
    "linkedin": {"resolution": "1080x1350", "aspectRatio": "4:5", "format": "MP4", "fps": 30, "audioCodec": "AAC"},
}


def detect_production_mode(job: dict) -> tuple[str, Path | None]:
    talking_head = Path(job.get("talkingHeadAsset", "assets/talking_head/nat_intro_01.mp4"))
    if talking_head.exists() and not _is_placeholder(talking_head):
        return "hybrid", talking_head
    declared = job.get("productionMode")
    if declared:
        return declared, None
    return "faceless", None


def collect_missing_assets(job: dict) -> list[dict]:
    missing = []
    seen: set[str] = set()

    def add(entry: dict) -> None:
        if entry["path"] not in seen:
            seen.add(entry["path"])
            missing.append(entry)

    for item in job.get("videoPlan", []):
        clip_path = Path("assets") / item["clip"]
        if not clip_path.exists() or clip_path.stat().st_size == 0:
            status = "missing"
        else:
            # Placeholders are generated by this repo; flag them so Nat knows what to replace.
            status = "placeholder" if _is_placeholder(clip_path) else "real"
        if status != "real":
            default_hint = CHAPTER_CARD_HINT if "chapter_cards/" in item["clip"] else "Record or export this clip."
            add({
                "path": str(clip_path),
                "status": status,
                "howToCreate": REAL_ASSET_HINTS.get(item["clip"], default_hint),
            })

    for th in job.get("talkingHead", {}).get("clips", []):
        th_path = Path(th)
        if not th_path.exists() or _is_placeholder(th_path):
            add({
                "path": str(th_path),
                "status": "placeholder" if th_path.exists() else "missing",
                "howToCreate": "Film a talking-head clip: chest-up, dark backdrop, key light on face, direct eye contact.",
            })

    voiceover = Path(job.get("voiceover", ""))
    if job.get("voiceover") and not voiceover.exists():
        add({
            "path": str(voiceover),
            "status": "missing",
            "howToCreate": "Record the script as a WAV (quiet room, phone or USB mic is fine).",
        })

    music_dir = Path("assets/music")
    has_music = music_dir.exists() and (any(music_dir.glob("*.mp3")) or any(music_dir.glob("*.wav")))
    if not has_music:
        add({
            "path": "assets/music/corporate_tech_pulse_01.mp3",
            "status": "missing",
            "howToCreate": "Download a royalty-free clean corporate tech track (YouTube Audio Library works). Optional: video renders without it.",
        })
    return missing


def _is_placeholder(clip_path: Path) -> bool:
    marker = clip_path.with_suffix(".placeholder")
    return marker.exists()


def capcut_edit_plan(job: dict, mode: str, platform: str) -> str:
    lines = [
        f"# CapCut Edit Plan — {job.get('jobName', 'job')}",
        "",
        f"Production mode: **{mode}**",
        f"Platform preset: **{platform}** (1080x1920, 9:16, MP4, 30fps, AAC)" if platform == "shorts" else f"Platform preset: **{platform}**",
        "",
        "## Timeline order",
        "",
    ]
    t = 0.0
    for i, item in enumerate(job["videoPlan"], start=1):
        end = t + item["duration"]
        lines.append(
            f"{i}. `{item['clip']}` — {t:.0f}s to {end:.0f}s — overlay: \"{item['overlayText']}\" — motion: {item.get('motion', 'none')} — transition: {item.get('transition', 'cut')}"
        )
        t = end
    lines += [
        "",
        f"Total draft runtime: ~{t:.0f}s",
        "",
        "## Caption styling (AI Email Dev brand)",
        "",
        "- Bold white text (#F5F8FF), bottom safe zone, semi-transparent navy background.",
        "- Amber highlight (#FFB950) on proof phrases: \"overlooked path\", \"Brief → AI Agent → HTML → QA → ZIP\", \"proof-of-work\".",
        "- Import `04_captions.srt` for editable captions, or use CapCut auto-captions from the voiceover and correct against the SRT.",
        "",
        "## Voice + music",
        "",
        "- Voiceover at 100%. Music bed at 10% to 18% under voice.",
        "- Enable music ducking under voice if using CapCut auto-ducking.",
        "- If no licensed music track is available, ship voice-only. Voice is primary.",
        "",
        "## Punch-in moments",
        "",
        "- Punch in ~110% on \"AI-powered email development\" (0:07).",
        "- Punch in on the ZIP package reveal (\"Proof-of-Work Package\").",
        "- Hold steady on the flow map (Learn AI. Build proof. Grow your value.).",
        "",
        "## Finishing steps",
        "",
        "1. New CapCut project, import the whole `capcut_import/` folder.",
        "2. Drop `01_draft_short.mp4` on the timeline as the base.",
        "3. Replace placeholder segments with real screen recordings as they become available (same order/durations).",
        "4. Add voiceover track, align caption timings to voice.",
        "5. Apply caption style above, add subscribe end-card emphasis on the last 5 seconds.",
        "6. Export: 1080x1920, 9:16, MP4, 30fps, high bitrate, AAC audio.",
        "",
        "Do not automate publishing. Human review before upload.",
    ]
    if mode == "hybrid":
        lines += [
            "",
            "## Hybrid mode",
            "",
            "- Overlay `assets/talking_head/nat_intro_01.mp4` as picture-in-picture (lower-right) during the intro (0:00–0:11) and the CTA (final 8s).",
            "- Use the `talking_head_tech_frame` overlay if available.",
        ]
    return "\n".join(lines)


def production_notes(job: dict, mode: str, missing: list[dict], voiceover_used: bool, music_used: bool) -> str:
    lines = [
        f"# Production Notes — {job.get('jobName', 'job')}",
        "",
        f"- Brand: {job.get('brand', 'AI Email Dev')}",
        f"- Slogan: {job.get('slogan', 'Learn AI. Build proof. Grow your value.')}",
        f"- Production mode: **{mode}** " + ("(talking-head asset found)" if mode == "hybrid" else "(no talking-head asset found; faceless first)"),
        f"- Visual style: {job.get('visualStyle', 'brief_to_zip_flow_map')} (fallback: {job.get('fallbackVisualStyle', 'enterprise_grid_pulse')})",
        f"- Voiceover in draft render: {'yes' if voiceover_used else 'NO — silent draft, record voiceover next'}",
        f"- Music in draft render: {'yes' if music_used else 'no (optional; voice is primary)'}",
        "",
        "## Compliance",
        "",
        "- No income guarantees, no get-rich-quick claims. Practical, motivational, technical tone.",
        "",
        "## Missing / placeholder assets",
        "",
    ]
    if missing:
        for m in missing:
            lines.append(f"- `{m['path']}` — {m['status']}. {m['howToCreate']}")
    else:
        lines.append("- None. All assets are real.")
    lines += [
        "",
        "## Next actions",
        "",
        "1. Record the voiceover (short script) → save as `assets/voiceover/intro-video_01_voiceover.wav`.",
        "2. Record/export the screen-recording b-roll listed above (highest impact: html_email_code, chatgpt_agent_prompt, zip_package_folder).",
        "3. Re-run the full pipeline with `--mode full --voiceover assets/voiceover/intro-video_01_voiceover.wav`.",
        "4. Finish in CapCut using `capcut_edit_plan.md`, then human review before publish.",
    ]
    return "\n".join(lines)


def longform_expansion(job: dict) -> str:
    return "\n".join([
        f"# Long-form Expansion — {job.get('jobName', 'job')}",
        "",
        "Use this outline to expand the Short into a 5–8 minute long-form video (1920x1080).",
        "",
        "## Outline",
        "",
        "1. Hook (0:00–0:30): The overlooked path into enterprise marketing.",
        "2. Why email development is enterprise infrastructure (0:30–1:30).",
        "3. Who this channel is for: overlooked builders, career changers, grads, stuck marketers (1:30–2:30).",
        "4. The skill stack: HTML email → QA → personalization → automation → AI workflows (2:30–4:00).",
        "5. Brief-to-ZIP demo teaser: brief in, full production package out (4:00–6:00).",
        "6. Proof-of-work philosophy: evidence over motivation (6:00–7:00).",
        "7. CTA: Subscribe to become the AI-powered email developer companies cannot ignore (7:00–end).",
        "",
        "## Long script draft",
        "",
        job.get("longScript", ""),
        "",
        "## Production notes",
        "",
        "- Reuse the Short's b-roll, extended with full screen-recording walkthroughs.",
        "- Add chapter cards using brand colors (navy #09122D, teal #135D66, electric blue #3B82F6, amber #FFB950).",
        "- Talking-head sections add credibility once `assets/talking_head/` clips exist.",
    ])


def main() -> None:
    parser = argparse.ArgumentParser(description="Build the CapCut-ready review package for a job.")
    parser.add_argument("--job", required=True)
    parser.add_argument("--platform", default="shorts")
    parser.add_argument("--voiceover", default=None)
    parser.add_argument("--music", default=None)
    args = parser.parse_args()

    job_path = Path(args.job)
    job = json.loads(job_path.read_text(encoding="utf-8"))
    stem = job_path.stem

    review_dir = Path("output/review") / stem
    import_dir = review_dir / "capcut_import"
    review_dir.mkdir(parents=True, exist_ok=True)
    import_dir.mkdir(parents=True, exist_ok=True)

    mode, talking_head = detect_production_mode(job)
    missing = collect_missing_assets(job)

    # Core outputs from earlier pipeline stages
    short_src = Path("output/shorts") / f"{stem}.mp4"
    thumb_src = Path("output/thumbnails") / f"{stem}.jpg"
    srt_src = Path("output/captions") / f"{stem}.srt"

    if short_src.exists():
        shutil.copy2(short_src, review_dir / "short.mp4")
    if thumb_src.exists():
        shutil.copy2(thumb_src, review_dir / "thumbnail.jpg")
    if srt_src.exists():
        shutil.copy2(srt_src, review_dir / "captions.srt")

    (review_dir / "metadata.json").write_text(
        json.dumps(job["metadata"], indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )

    voiceover_path = Path(args.voiceover) if args.voiceover else Path(job.get("voiceover", ""))
    voiceover_used = bool(args.voiceover) and Path(args.voiceover).exists()
    music_path = Path(args.music) if args.music else None
    music_used = bool(music_path and music_path.exists())

    (review_dir / "production_notes.md").write_text(
        production_notes(job, mode, missing, voiceover_used, music_used) + "\n", encoding="utf-8"
    )
    missing_lines = [f"# Missing / Placeholder Assets — {stem}", ""]
    if missing:
        for m in missing:
            missing_lines.append(f"- `{m['path']}` — **{m['status']}**. {m['howToCreate']}")
    else:
        missing_lines.append("- None. All assets are real.")
    (review_dir / "missing_assets.md").write_text("\n".join(missing_lines) + "\n", encoding="utf-8")

    # Preserve a hand-authored edit plan if one exists; otherwise generate the standard one.
    edit_plan_path = review_dir / "capcut_edit_plan.md"
    if not edit_plan_path.exists():
        edit_plan_path.write_text(capcut_edit_plan(job, mode, args.platform) + "\n", encoding="utf-8")
    if args.platform == "shorts":
        (review_dir / "longform_expansion.md").write_text(longform_expansion(job) + "\n", encoding="utf-8")

    # CapCut import folder
    import_files = []
    if short_src.exists():
        shutil.copy2(short_src, import_dir / "01_draft_short.mp4")
        import_files.append({"file": "01_draft_short.mp4", "role": "base timeline video", "status": "ready"})
    if voiceover_path and voiceover_path.exists():
        dest = import_dir / f"02_voiceover{voiceover_path.suffix}"
        shutil.copy2(voiceover_path, dest)
        import_files.append({"file": dest.name, "role": "primary voiceover", "status": "ready"})
    else:
        import_files.append({"file": "02_voiceover.wav", "role": "primary voiceover", "status": "missing — record and re-run full mode"})
    if music_used:
        dest = import_dir / f"03_music{music_path.suffix}"
        shutil.copy2(music_path, dest)
        import_files.append({"file": dest.name, "role": "music bed at 10-18%", "status": "ready"})
    else:
        import_files.append({"file": "03_music.mp3", "role": "music bed at 10-18%", "status": "optional — add royalty-free corporate tech track"})
    if srt_src.exists():
        shutil.copy2(srt_src, import_dir / "04_captions.srt")
        import_files.append({"file": "04_captions.srt", "role": "editable captions", "status": "ready"})
    if thumb_src.exists():
        shutil.copy2(thumb_src, import_dir / "05_thumbnail.jpg")
        import_files.append({"file": "05_thumbnail.jpg", "role": "thumbnail reference", "status": "ready"})

    style_asset = Path("assets/motion/backgrounds") / f"{job.get('visualStyle', 'brief_to_zip_flow_map')}.mp4"
    if style_asset.exists():
        shutil.copy2(style_asset, import_dir / "06_motion_background.mp4")
        import_files.append({"file": "06_motion_background.mp4", "role": "motion background", "status": "ready"})
    if talking_head:
        shutil.copy2(talking_head, import_dir / "07_talking_head.mp4")
        import_files.append({"file": "07_talking_head.mp4", "role": "talking-head PiP overlay", "status": "ready"})

    manifest = {
        "job": stem,
        "platform": args.platform,
        "productionMode": mode,
        "exportPreset": EXPORT_PRESETS.get(args.platform, EXPORT_PRESETS["shorts"]),
        "importFiles": import_files,
        "missingAssets": missing,
        "editPlan": "capcut_edit_plan.md",
        "notes": "Manual CapCut finishing only. No automated publishing or upload.",
    }
    (review_dir / "capcut_import_manifest.json").write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )

    print(f"✅ Review package written: {review_dir}")
    if missing:
        print(f"⚠️ {len(missing)} missing/placeholder assets — see production_notes.md")


if __name__ == "__main__":
    main()
